// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeapevrjjgoinczpzfbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lYXBldnJqamdvaW5jenB6ZmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzOTgxMDcsImV4cCI6MjA1ODk3NDEwN30.1FNKTkyasI6eMW8v5g6X183_czxmJkkSNTsTN_b41tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);